### ISSUE TITLE
f_dec referenced before assignment when running gpulearn_z_x.py mnist

### ISSUE THREAD

**Issue by AjayTalati** [dpkingma/nips14-ssl#2]
Hi, I tried running the unsupervised M1 model on the mnist dataset, using 

`sh python run gpulearn_z_x.py mnist`, 

and got

`NameError: free variable 'f_dec' referenced before assignment in enclosing scope`

Looking at the code for the supervised M1+M2 model, I think the line,

`f_enc, f_dec = lambda x:x, lambda x:x`

might have been deleted  around line  41, of  `gpulearn_z_x.py` ? Might also be needed for some of the other cases, with no preprocessing, `mnist_binarized`, `freyface`, `freyface_bernoulli`, `norb`, etc, but I have'nt downloaded the data for these yet? 

Downloaded the 3 datasets for `svhn`, from `http://ufldl.stanford.edu/housenumbers/`, and that's fine.  

Thanks :+1:

**Comment by escopeta** [comment]
I also have this problem, were you able to fix this by adding this "f_enc, f_dec = lambda x:x, lambda x:x" AjayTalati?

**Comment by AjayTalati** [comment]
Hi escopeta, I can't remember for sure but I think the fix works. 

If I understand the code correctly `f_dec` is just used for graphics output and not for the NN or VAE parts of the code.

I'm not at my machine at the moment, but I'll reply when I try it out.

**Comment by dpkingma** [comment]
Thanks for this bug report. It's been solved now by adding back the line "f_enc, f_dec = lambda x:x, lambda x:x". Running "python run_gpulearn_z_x.py mnist" now happens without problems.
